### ISSUE TITLE
Carousel is not working with ngFor

### ISSUE THREAD

**Issue by damisadam** [kappys1/angular2-carousel#7] opened 2018-05-17 10:49 UTC
Please check this . When i apply for loop then this show blank screen.

`<carousel-component  class="cube-mode" [mode]="'horizontal'" [perspective]="100" #topCarousel>

  <div  class="item-carousel" style="background-color: wheat; width: 200px" *ngFor='let a of songs let i = index;'   ></div>

</carousel-component>`

**Comment by kappys1** [comment] 2018-05-17 14:19
Can you check the error in console and show me?
Thanks

**Comment by danielfigueroaj** [comment] 2018-05-17 21:03
Same here.

@kappys1  there's no error in console, it seems there is some issue with the 'width' property, when I use ngFor, that property is 0px.

this is the output html when creating a static carousel with 3 elements:

```
<carousel-component _ngcontent-c2="" _nghost-c3="" ng-reflect-more-pair-slides="0" class=" ready"><div _ngcontent-c3="" class="container" style="perspective: 2000px; width: 600px; height: 400px;">
  <div _ngcontent-c3="" class="carousel" style="touch-action: pan-y; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); transform: translateZ(-744px) rotateY(-90deg); transition: transform 300ms;">
    
    <div _ngcontent-c2="" class="item-carousel" style="transform: rotateY(0deg) translateZ(744px);">
              <img _ngcontent-c2="" src="http://vignette3.wikia.nocookie.net/despicableme/images/1/1d/Kevin_minions.png/revision/latest?cb=20160929061515">
            </div><div _ngcontent-c2="" class="item-carousel" style="transform: rotateY(45deg) translateZ(744px);">
              <img _ngcontent-c2="" src="http://vignette3.wikia.nocookie.net/despicableme/images/1/1d/Kevin_minions.png/revision/latest?cb=20160929061515">
            </div><div _ngcontent-c2="" class="item-carousel actual" style="transform: rotateY(90deg) translateZ(744px);">
              <img _ngcontent-c2="" src="http://vignette3.wikia.nocookie.net/despicableme/images/1/1d/Kevin_minions.png/revision/latest?cb=20160929061515">
            </div>
  </div>
</div></carousel-component>
```
look at the style part, it has: **style="perspective: 2000px; width: 600px; height: 400px;"**

and this one is using ngfor:

```
<carousel-component _ngcontent-c2="" _nghost-c3="" ng-reflect-more-pair-slides="0" ng-reflect-angle="45" ng-reflect-ratio-scale="1" ng-reflect-margin="0" ng-reflect-perspective="2000" ng-reflect-time-to-slide="300" ng-reflect-lock-slides="false" ng-reflect-initial-slide="0" class=" ready"><div _ngcontent-c3="" class="container" style="perspective: 2000px; width: 0px; height: 0px;">
  <div _ngcontent-c3="" class="carousel" style="touch-action: pan-y; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); transform: translateZ(0px) rotateY(45deg);">
    
    <!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><div _ngcontent-c2="" class="item-carousel">
              <img _ngcontent-c2="" src="http://vignette3.wikia.nocookie.net/despicableme/images/1/1d/Kevin_minions.png/revision/latest?cb=20160929061515">
            </div><div _ngcontent-c2="" class="item-carousel">
              <img _ngcontent-c2="" src="http://vignette3.wikia.nocookie.net/despicableme/images/1/1d/Kevin_minions.png/revision/latest?cb=20160929061515">
            </div><div _ngcontent-c2="" class="item-carousel">
              <img _ngcontent-c2="" src="http://vignette3.wikia.nocookie.net/despicableme/images/1/1d/Kevin_minions.png/revision/latest?cb=20160929061515">
            </div>
  </div>
</div></carousel-component>
```
this is the generated style using ngfor
**style="perspective: 2000px; width: 0px; height: 0px;"**

Thank you

**Comment by danielfigueroaj** [comment] 2018-05-17 21:22
I'm not sure that's the problem, I modified the below lines:

```
this.containerElm.nativeElement.style.width = '600px';
//this.containerElm.nativeElement.style.height = this.carousel.maxHeigthSize + 'px';
this.containerElm.nativeElement.style.height = '400px';
```

but the carousel is still blank

**Comment by kappys1** [comment] 2018-05-17 22:01
Let me see because I need test it!
If you can, could you do the example in plunkr or send me a photo for view the mistake ?

Thanks

**Comment by danielfigueroaj** [comment] 2018-05-17 22:14
I took two screen shots, but you can see the image is not shown fine

![screenshot from 2018-05-17 17-10-56](https://user-images.githubusercontent.com/16999346/40206465-cc6bfa7a-59f5-11e8-93ee-b240a4cff6a8.png)
![screenshot from 2018-05-17 17-10-58](https://user-images.githubusercontent.com/16999346/40206466-cc808814-59f5-11e8-8188-87421c5e1e48.png)

**Comment by kappys1** [comment] 2018-05-17 23:56
I think that you code have a mistake.
I did a example with ngFor in the angular2-carousel page and it work fine with ngFor:
you can see the example here : [Sample Example - first example](https://kappys1.github.io/angular2-carousel/demo)
and code : [Code Sample Example - first example](https://github.com/kappys1/angular2-carousel/tree/web-doc/src/app/components/simple-carousel-from-service)

I use a div with background-image but is the same with a img tag, you can put anything inside the container

**Comment by kappys1** [comment] 2018-05-18 11:33
tell us if you have got solve the problem for close the issue!

Thanks
if you like the Module please give me a star =)

**Comment by danielfigueroaj** [comment] 2018-05-18 14:47
Yes, it is working fine, thank you

![screenshot from 2018-05-18 09-44-14](https://user-images.githubusercontent.com/16999346/40241357-6efef046-5a80-11e8-8a5d-67ce9ba9ef72.png)

**Comment by kappys1** [comment] 2018-05-18 15:18
Thanks I close the issue!
If you want you can give me a start for help me! 

Thanks!!!

**Closed as completed by kappys1** 2018-05-18 15:18 UTC

**Comment by LoveenDyall** [comment] 2018-06-11 21:44
I'm currently facing the same issue.

How was this resolved?

**Comment by kappys1** [comment] 2018-06-13 05:50
I did a example with ngFor in the angular2-carousel page and it work fine with ngFor:
you can see the example here : [Sample Example - first example](https://kappys1.github.io/angular2-carousel/demo)
and code : [Code Sample Example - first example](https://github.com/kappys1/angular2-carousel/tree/web-doc/src/app/components/simple-carousel-from-service)

**Comment by LoveenDyall** [comment] 2018-06-15 23:25
Hi It still isn't working although your example works locally.

I believe this is due to using a div wrapper with *ngIf applied. If the containing element is not displayed, then the carousel styles do not get applied correctly i.e. the transform (rotation etc..)

Can you please advise as I think this is a bug?

**Comment by kappys1** [comment] 2018-06-15 23:32
Can you let me a example please?

Equally I will try to reproduce and check this and if is a bug, I will solve it!

Thanks for tell me!

**Comment by LoveenDyall** [comment] 2018-06-15 23:37
<img width="1425" alt="error" src="https://user-images.githubusercontent.com/28401652/41493256-556904c6-70fd-11e8-966f-cf3863847d72.png">


`.carousel_top .container {
	width: 60%!important;
	height: 27em!important;
}

.item-carousel {
	border: none!important;
	border-bottom-right-radius: 20px;
	-webkit-box-shadow: 0px 0px 13px -2px rgba(0,0,0,0.75);
	-moz-box-shadow: 0px 0px 13px -2px rgba(0,0,0,0.75);
	box-shadow: 0px 0px 13px -2px rgba(0,0,0,0.75);
	width: 100%;
	height: 100%;
	opacity: 1!important;
}`

**Comment by LoveenDyall** [comment] 2018-06-15 23:40
<img width="1417" alt="error" src="https://user-images.githubusercontent.com/28401652/41493312-dae9252c-70fd-11e8-89d3-eaba6a831ca3.png">
`
:host carousel-component{
  border: 1px solid black;
  display: block;
  overflow: hidden;
  padding: 8vh 6vh;
  width: 75%;
  margin: 0 auto;
  margin-top: 2vh;
}

.button-toggle{
  font-size: 1.8vh;
  padding: 1vh;
  margin-bottom: 1vh;
}
h1{
  font-size: 3vh;
  font-weight: 200;
  color: #1976d2;
}

.item-carousel{
  background-color: white;
  display: -ms-flexbox!important;
  display: -webkit-flex!important;
  display: flex!important;
  -webkit-flex-direction: row;
  -ms-flex-direction: row;
  flex-direction: row;
  -webkit-flex-wrap: nowrap;
  -ms-flex-wrap: nowrap;
  flex-wrap: nowrap;
  -webkit-justify-content: center;
  -ms-flex-pack: center;
  justify-content: center;
  -webkit-align-content: stretch;
  -ms-flex-line-pack: stretch;
  align-content: stretch;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
  width: 23vh!important;
  height: 20vh!important;
  top:0vh;
}


.item-carousel div,
.item-carousel img{
  height: 100%;
  width: 100%;
}
.item-carousel div{
  background-size: contain;
  background-repeat: no-repeat;
  background-position: center center;
}

.parameter-option{
  margin-right: 2vh;
}
.parameters-content{
  font-size: 1.8vh;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
  -webkit-flex-direction: row;
  -ms-flex-direction: row;
  flex-direction: row;
  -webkit-flex-wrap: wrap;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  -webkit-justify-content: flex-start;
  -ms-flex-pack: start;
  justify-content: flex-start;
  -webkit-align-content: stretch;
  -ms-flex-line-pack: stretch;
  align-content: stretch;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
}
.parameters-content button,
.parameters-content select,
.parameters-content input{
  font-size: 1.5vh;
}
p.show-code{
  color: #ab2300;
}
p{
  font-size: 1.8vh;
}

:host carousel-component.style-carousel.ready .item-carousel{
  -webkit-transition: all 500ms !important;
  -moz-transition:all 500ms!important;
  -o-transition: all 500ms!important;
  transition: all 500ms!important;
}
:host carousel-component.style-carousel.ready .item-carousel.actual{
  height: 30vh!important;
  top:-2.5vh;
}

:host carousel-component.cube-mode.ready >>> .container{
  perspective: 10vh!important;
}

/* Small devices (tablets, 768px and up) */
@media (min-width: 768px) {
  h1{
    font-size: 2.5vh;
  }
  .button-toggle,
  p{
    font-size: 1.7vh;
  }
  .parameters-content {
    font-size: 1.7vh;
  }


}


/* Large devices (large desktops, 1200px and up) */
@media (min-width: 1200px) {
  :host carousel-component{
    width: 60%;
  }
  .item-carousel{
    width: 28vh!important;
    height: 25vh!important;
  }
  h1{
    font-size: 2.7vh;
  }
  .button-toggle{
    font-size: 1.6vh;
  }

}
@media (min-width: 2000px) {
  :host carousel-component.cube-mode.ready >>> .container{
    perspective: 15vh!important;
  }
}`

**Comment by kappys1** [comment] 2018-06-16 09:47
Okey but you only send me a css, the html with the component?

**Comment by LoveenDyall** [comment] 2018-06-16 15:57
[Archive 2.zip](https://github.com/kappys1/angular2-carousel/files/2108293/Archive.2.zip)

Hey Thanks for the response.

I've attached the html and css component files. The carousel at the top works fine, it's the second carousel that doesn't seem to display.

**Comment by kappys1** [comment] 2018-06-17 23:54
Hi, I update the Library, you can check if with this is solved!
Now is not required reInit() when you want to add dynamic content.

Thanks

**Comment by kappys1** [comment] 2018-06-17 23:57
@danielfigueroaj I update the Library , now is not required reInit() when you want to add dynamic content.

**Comment by LoveenDyall** [comment] 2018-06-18 12:44
works perfectly.

thanks

**Comment by kappys1** [comment] 2018-06-18 17:00
@LoveenDyall Okey! Thanks for all!!
